# SPDX-FileCopyrightText: 2024 Nikita Chernyi
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure KeyDB paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ keydb_uid }}"
    group: "{{ keydb_gid }}"
  with_items:
    - "{{ keydb_base_path }}"
    - "{{ keydb_data_path }}"

- name: Ensure KeyDB environment variables file created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ keydb_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ keydb_uid }}"
    group: "{{ keydb_gid }}"
  with_items:
    - "keydb.conf"

- name: Ensure KeyDB container image is pulled
  community.docker.docker_image:
    name: "{{ keydb_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ keydb_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else keydb_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure KeyDB container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ keydb_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure KeyDB systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/keydb.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ keydb_identifier }}.service"
    mode: "0644"
