# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform KeyDB installation tasks
  when: keydb_enabled | bool
  tags:
    - setup-all
    - setup-keydb
    - install-all
    - install-keydb
  block:
    - name: Validate KeyDB configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install KeyDB
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform KeyDB uninstallation tasks
  when: not keydb_enabled | bool
  tags:
    - setup-all
    - setup-keydb
  block:
    - name: Uninstall KeyDB
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
