# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of KeyDB service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ keydb_identifier }}.service"
  register: keydb_service_stat

- when: keydb_service_stat.stat.exists | bool
  block:
    - name: Ensure KeyDB systemd service is stopped
      ansible.builtin.systemd:
        name: "{{ keydb_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure KeyDB systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ keydb_identifier }}.service"
        state: absent

- name: Check existence of KeyDB local data path
  ansible.builtin.stat:
    path: "{{ keydb_data_path }}"
  register: keydb_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- when: keydb_data_path_stat.stat.exists | bool
  name: Notify if KeyDB local data remains
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: You are not using a local KeyDB instance, but some old data remains from before in `{{ keydb_data_path }}`. Feel free to delete it."
        ]
      }}

