---

- name: Check existence of keydb service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ keydb_identifier }}.service"
  register: keydb_service_stat

- when: keydb_service_stat.stat.exists | bool
  block:
    - name: Ensure keydb is stopped
      ansible.builtin.systemd:
        name: "{{ keydb_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure keydb systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ keydb_identifier }}.service"
        state: absent

- name: Check existence of keydb local data path
  ansible.builtin.stat:
    path: "{{ keydb_data_path }}"
  register: keydb_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- when: keydb_data_path_stat.stat.exists | bool
  name: Notify if keydb local data remains
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: You are not using a local keydb instance, but some old data remains from before in `{{ keydb_data_path }}`. Feel free to delete it."
        ]
      }}

