# SPDX-FileCopyrightText: 2024 Nikita Chernyi
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of KeyDB service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ keydb_identifier }}.service"
  register: keydb_service_stat

- name: Uninstall KeyDB systemd services and files
  when: keydb_service_stat.stat.exists | bool
  block:
    - name: Ensure KeyDB systemd service is stopped
      ansible.builtin.systemd:
        name: "{{ keydb_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure KeyDB systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ keydb_identifier }}.service"
        state: absent

    - name: Ensure KeyDB environment variables file does not exist
      ansible.builtin.file:
        path: "{{ keydb_base_path }}/{{ item }}"
        state: absent
      with_items:
        - keydb.conf

    - name: Ensure KeyDB image source files path does not exist
      ansible.builtin.file:
        path: "{{ keydb_container_image_self_build_src_files_path }}"
        state: absent

    - name: Ensure KeyDB container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ keydb_container_network }}"
        state: absent

    - name: Ensure KeyDB container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ keydb_container_network }}
      register: network_deletion_result
      changed_when: keydb_container_network in network_deletion_result.stdout

- name: Check existence of KeyDB local data path
  ansible.builtin.stat:
    path: "{{ keydb_data_path }}"
  register: keydb_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if KeyDB local data remains
  when: keydb_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: You are not using a local KeyDB instance, but some old data remains from before in `" + keydb_data_path + "`. Feel free to delete it."
        ]
      }}
